### ISSUE TITLE
Webview inadaptée sur iPhone X

### ISSUE THREAD

**Issue by tJulianB** [ezeeworld/WiiishInApp-iOS-SDK#1]
Bonjour,

merci de corriger votre Webview sur iPhone X : le bouton Fermer se met sous l'état réseau/batterie et ne fonctionne donc pas.

Merci

**Comment by tJulianB** [comment]
![image](https://user-images.githubusercontent.com/13127772/36211855-a9a6e3ba-11a2-11e8-953c-656ea0df255b.png)

**Comment by stspenle** [comment]
Bonjour,

Une nouvelle version du SDK est disponible avec l'adaptation à l'iPhone X..

**Comment by tJulianB** [comment]
Bonjour, cette nouvelle version a exactement le même numéro que l'ancienne version, CocoaPods installe donc l'ancienne.
Pouvez-vous également faire une nouvelle _release_ ? Merci

**Comment by stspenle** [comment]
Rebonjour, la release a été faite. Désolée pour le contre temps

**Comment by tJulianB** [comment]
Bonjour la release n'a jamais corrigé le bug : https://github.com/ezeeworld/WiiishInApp-iOS-SDK/issues/2

**Comment by tJulianB** [comment]
Toujours le cas même avec la version 1.2.6 ...

**Comment by tJulianB** [comment]
Toujours le cas aussi bien avec la version du 28/2 même qu'avec la version 1.2.6 ... #2
